# [Info]
site_name: Friki Docs
site_url: https://frikilinux.github.io
site_author: Frikilinux
site_description: Awesome docs for everything

# [UI]
## [top]
theme:
  name: material
  palette: 
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: TOGGLE
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
  language: en
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs
## [top-right corner]
repo_url: https://github.com/Frikilinux/frikilinux.github.io
repo_name: frikilinux.github.io
## [bottom-left corner]
copyright: Copyright &copy; 2022 Frikilinux
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1234
      name: Bilibili | BLIBLIBLI
    - icon: fontawesome/brands/github
      link: https://github.com/Frikilinux
      name: GitHub | Frikilinux

# [Navigtion]
nav:
  - Servers: 
    - server/index.md 

# [Extensions]
plugins:
  - search
  - tags
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      # linenums: true
      # auto_title: true
  - pymdownx.superfences
  - meta
extra_javascript:
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - mkdocs/css/no-footer.css
  - mkdocs/css/unordered-list-symbols.css
